export const HtmlElements: string[] = [
    'dir', 'div', 'dl', 'dt', 'em', 'embed', 'fieldset', 'font', 'form', 'frame', 'frameset',
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'head', 'hr', /* 'html',*/ 'hype', 'i', 'iframe', 'img',
    'video', 'track', 'time', 'tfoot', 'tbody', 'summary', 'source', 'section',
    'ruby', 'rt', 'rp', 'q', 'progress', 'output', 'optgroup', 'object', 'nav',
    'meter', 'menuitem', 'mark', 'main', 'keygen', 'header', 'footer', 'figure',
    'figcaption', 'dialog', 'details', 'datalist', 'canvas', 'bdo', 'bdi', 'audio',
    'aside', 'article', 'acronym', 'abbr', 'sup', 'del', 'textarea', 'th', 'title',
    'tr', 'tt', 'u', 'ul', 'var', 'wbr', 'xmp', 'input', 'isindex', 'kbd', 'label',
    'legend', 'li', 'link', 'listing', 'map', 'marquee', 'menu', 'meta', 'multicol',
    'nobr', 'noembed', 'noframes', 'noscript', 'ol', 'option', 'p', 'param', 'plaintext',
    'pre', 's', 'samp', 'script', 'select', 'small', 'sound', 'spacer', 'span', 'strong',
    'style', 'sub', 'table', 'thead', 'td', 'a', 'address', 'app', 'applet', 'area', 'b',
    'base', 'basefont', 'bgsound', 'big', 'blink', 'blockquote', /* 'body',*/ 'br', 'button',
    'caption', 'center', 'cite', 'code', 'col', 'colgroup', 'comment', 'dd', 'ins', 'dfn',
]
